import type { DraftPacket, DraftPacketType } from '@/arkham/draft/types'

export const ZOEY_INVESTIGATOR_CODE = '02001'
export const ZOEY_INVESTIGATOR_NAME = 'Zoey Samaras'
export const ZOEY_SIGNATURE_CODE = '02006'
export const ZOEY_SIGNATURE_WEAKNESS_CODE = '02007'
export const RANDOM_BASIC_WEAKNESS_CODE = '01000'
export const MIDNIGHT_MASKS_SCENARIO_ID = '01120'
export const DRAFT_MOCK_CAMPAIGN_NAME = 'Draft Mock - The Midnight Masks'
export const DRAFT_MOCK_DECK_NAME = 'Draft Zoey - The Midnight Masks'

export const roundPacketPreferences: readonly DraftPacketType[][] = [
  ['Weapon Core', 'Combat Burst'],
  ['Weapon Core', 'Combat Burst'],
  ['Economy', 'Flex'],
  ['Combat Burst', 'Engage/Protect'],
  ['Soak/Defense', 'Will Defense'],
  ['Clue Utility', 'Flex'],
  ['Weapon Core', 'Engage/Protect'],
  ['Will Defense', 'Soak/Defense'],
  ['Economy', 'Clue Utility'],
  ['Flex', 'Combat Burst', 'Weapon Core'],
]

export const zoeyMockPackets: readonly DraftPacket[] = [
  {
    id: 'weapon-core-machete',
    source: 'Core Guardian',
    type: 'Weapon Core',
    label: 'Blade and Backup',
    description: 'A primary melee weapon with flexible backup tools.',
    cards: ['01020', '01086', '02184'],
  },
  {
    id: 'weapon-core-firearm',
    source: 'Core Guardian',
    type: 'Weapon Core',
    label: 'Sidearm Kit',
    description: 'A firearm package with a tutor and extra weapon density.',
    cards: ['01016', '02184', '01086'],
  },
  {
    id: 'weapon-core-heavy',
    source: 'Core Guardian',
    type: 'Weapon Core',
    label: 'Prepared Arsenal',
    description: 'Find a real weapon and keep your hands productive.',
    cards: ['01020', '01016', '02147'],
  },
  {
    id: 'weapon-core-budget',
    source: 'Core Neutral',
    type: 'Weapon Core',
    label: 'Street Tools',
    description: 'Cheap weapons plus setup help for early turns.',
    cards: ['01086', '01020', '01088'],
  },
  {
    id: 'combat-burst-clean-hit',
    source: 'Core Guardian',
    type: 'Combat Burst',
    label: 'Clean Hit',
    description: 'Skills and events that convert tests into damage.',
    cards: ['01025', '01091', '01022'],
  },
  {
    id: 'combat-burst-overpower',
    source: 'Core Neutral',
    type: 'Combat Burst',
    label: 'Commit Hard',
    description: 'Combat icons, card flow, and a defensive cancel.',
    cards: ['01091', '01025', '01023'],
  },
  {
    id: 'combat-burst-bomb',
    source: 'Core Guardian',
    type: 'Combat Burst',
    label: 'Emergency Force',
    description: 'A burst damage event with resources to pay for it.',
    cards: ['01024', '01088', '01025'],
  },
  {
    id: 'combat-burst-engage',
    source: 'Dunwich Guardian',
    type: 'Combat Burst',
    label: 'Draw Them In',
    description: 'Engage enemies, hit harder, and keep tempo.',
    cards: ['02017', '01025', '01091'],
  },
  {
    id: 'economy-cache-training',
    source: 'Core Guardian',
    type: 'Economy',
    label: 'Fund the Fight',
    description: 'Resources and a repeatable place to spend them.',
    cards: ['01088', '01017', '01090'],
  },
  {
    id: 'economy-cache-weapon',
    source: 'Core Neutral',
    type: 'Economy',
    label: 'Cash and Steel',
    description: 'Pay for assets and keep weapon count high.',
    cards: ['01088', '01016', '01086'],
  },
  {
    id: 'economy-cache-protection',
    source: 'Core Guardian',
    type: 'Economy',
    label: 'Paid Protection',
    description: 'Resources, soak, and a defensive event.',
    cards: ['01088', '01021', '01023'],
  },
  {
    id: 'economy-composure',
    source: 'Core Neutral',
    type: 'Economy',
    label: 'Steady Nerves',
    description: 'Economy plus flexible commits for awkward tests.',
    cards: ['01088', '01093', '01089'],
  },
  {
    id: 'soak-dog-cop',
    source: 'Core Guardian',
    type: 'Soak/Defense',
    label: 'Allies on Watch',
    description: 'Classic Guardian allies for damage soak and combat.',
    cards: ['01021', '01018', '01023'],
  },
  {
    id: 'soak-first-aid',
    source: 'Core Guardian',
    type: 'Soak/Defense',
    label: 'Patch Up',
    description: 'A compact survival package for Midnight Masks pressure.',
    cards: ['01019', '02105', '01023'],
  },
  {
    id: 'soak-consumables',
    source: 'Dunwich Neutral',
    type: 'Soak/Defense',
    label: 'Pain Management',
    description: 'Cheap tools to smooth horror and damage spikes.',
    cards: ['02116', '02117', '01089'],
  },
  {
    id: 'soak-guarded-setup',
    source: 'Core Guardian',
    type: 'Soak/Defense',
    label: 'Guarded Setup',
    description: 'Soak, weapon setup, and a cancel for bad attacks.',
    cards: ['01021', '02184', '01023'],
  },
  {
    id: 'engage-taunt',
    source: 'Dunwich Guardian',
    type: 'Engage/Protect',
    label: 'Zoey Pull',
    description: 'Bring enemies to Zoey and profit from the fight.',
    cards: ['02017', '01020', '01025'],
  },
  {
    id: 'engage-cover',
    source: 'Core Guardian',
    type: 'Engage/Protect',
    label: 'Cover Fire',
    description: 'Protection, burst damage, and a backup weapon.',
    cards: ['01023', '01024', '01086'],
  },
  {
    id: 'engage-shortcut',
    source: 'Dunwich Utility',
    type: 'Engage/Protect',
    label: 'Close Distance',
    description: 'Movement utility with enough icons to stay useful.',
    cards: ['02022', '02017', '01091'],
  },
  {
    id: 'engage-badge',
    source: 'Core Guardian',
    type: 'Engage/Protect',
    label: 'Police Backup',
    description: 'A combat ally and enemy-control tools.',
    cards: ['01018', '02017', '01022'],
  },
  {
    id: 'clue-flashlight',
    source: 'Core Neutral',
    type: 'Clue Utility',
    label: 'Basic Investigation',
    description: 'Simple clue tools for a low-intellect Guardian.',
    cards: ['01087', '01090', '01093'],
  },
  {
    id: 'clue-hunch',
    source: 'Core Seeker Splash',
    type: 'Clue Utility',
    label: 'Fast Clue',
    description: 'A small Seeker splash to keep Midnight Masks moving.',
    cards: ['01037', '01087', '01090'],
  },
  {
    id: 'clue-deduction',
    source: 'Core Seeker Splash',
    type: 'Clue Utility',
    label: 'Focused Search',
    description: 'Commit icons and a flashlight for clue compression.',
    cards: ['01039', '01087', '01093'],
  },
  {
    id: 'clue-shortcut',
    source: 'Dunwich Utility',
    type: 'Clue Utility',
    label: 'Move and Look',
    description: 'Shortcut into useful locations and pick up clues.',
    cards: ['02022', '01087', '01090'],
  },
  {
    id: 'will-guts',
    source: 'Core Neutral',
    type: 'Will Defense',
    label: 'Hold Steady',
    description: 'Will icons and flexible commits for encounter checks.',
    cards: ['01089', '01093', '01017'],
  },
  {
    id: 'will-dodge',
    source: 'Core Guardian',
    type: 'Will Defense',
    label: 'Brace for Trouble',
    description: 'Will icons with protection against enemy attacks.',
    cards: ['01089', '01023', '01019'],
  },
  {
    id: 'will-consumables',
    source: 'Dunwich Neutral',
    type: 'Will Defense',
    label: 'Nerve Kit',
    description: 'Encounter icons plus cheap horror/damage smoothing.',
    cards: ['01089', '02116', '02117'],
  },
  {
    id: 'will-flex',
    source: 'Core Neutral',
    type: 'Will Defense',
    label: 'Balanced Icons',
    description: 'A safe packet when the deck needs test coverage.',
    cards: ['01089', '01092', '01093'],
  },
  {
    id: 'flex-core-neutral',
    source: 'Core Neutral',
    type: 'Flex',
    label: 'Core Staples',
    description: 'Useful cards that fit most draft decks.',
    cards: ['01088', '01087', '01093'],
  },
  {
    id: 'flex-guardian-basics',
    source: 'Core Guardian',
    type: 'Flex',
    label: 'Guardian Basics',
    description: 'Combat, soak, and evidence in one packet.',
    cards: ['01022', '01021', '01025'],
  },
  {
    id: 'flex-setup',
    source: 'Dunwich Guardian',
    type: 'Flex',
    label: 'Setup Tools',
    description: 'Find weapons and make room to hold them.',
    cards: ['02184', '02147', '01088'],
  },
  {
    id: 'flex-tempo',
    source: 'Dunwich Utility',
    type: 'Flex',
    label: 'Tempo Play',
    description: 'Move, fight, and cover an awkward test.',
    cards: ['02022', '01091', '01093'],
  },
]
